# BRSR / ESG practice question bank.
# Formats: plain MCQ | "table" (markdown) | "scenario" (text) | "chart" (bar/line spec) | "multi" (multi-select)
# Add questions by appending dicts in the same shape. "a" = index of correct option
# (or list of indices when "multi": True).

SEBI = "https://www.sebi.gov.in/legal/circulars/"
MCA = "https://www.mca.gov.in/"
GHG = "https://ghgprotocol.org/"

QUIZ_BANK = [
 {"q":"BRSR is mandatory for which listed entities?", "opts":["Top 100 by market cap","Top 500 by market cap","Top 1,000 by market cap","All listed companies"], "a":2, "why":"SEBI mandates BRSR for the top 1,000 listed entities by market capitalisation.", "link":SEBI},
 {"q":"BRSR replaced which earlier report?", "opts":["Business Responsibility Report (BRR)","Annual Compliance Report","CSR-1 Report","Sustainability Mandate Report"], "a":0, "why":"BRSR superseded the BRR format from FY 2022-23."},
 {"q":"How many NGRBC principles underpin BRSR?", "opts":["5","7","9","12"], "a":2, "why":"The NGRBC define nine principles.", "link":MCA},
 {"q":"Who published the NGRBC?", "opts":["SEBI","Ministry of Corporate Affairs","RBI","NITI Aayog"], "a":1, "why":"MCA published the NGRBC; SEBI operationalised it via BRSR.", "link":MCA},
 {"q":"BRSR Core KPIs require which level of assurance?", "opts":["No assurance","Limited assurance","Reasonable assurance","Internal audit only"], "a":2, "why":"SEBI's BRSR Core circular mandates reasonable assurance.", "link":SEBI},
 {"q":"Which are the sections of BRSR Comprehensive format?", "opts":["A & B only","A, B & C","1 to 9","Part I & II"], "a":1, "why":"A general disclosures, B management & process, C principle-wise performance."},
 {"q":"Section C of BRSR contains:", "opts":["Company profile","Policy checklist","Principle-wise quantitative & qualitative performance","Auditor's certificate"], "a":2, "why":"Section C maps essential and leadership indicators to the nine principles."},
 {"q":"Scope 1 emissions are:", "opts":["Direct emissions from owned/controlled sources","Emissions from purchased electricity","Supplier emissions","Employee commuting"], "a":0, "why":"GHG Protocol: Scope 1 = direct.", "link":GHG},
 {"q":"Scope 2 emissions arise from:", "opts":["Company vehicles","Purchased electricity/steam/heat/cooling","Waste disposal","Business travel"], "a":1, "why":"Scope 2 = purchased energy.", "link":GHG},
 {"q":"BRSR Core value-chain disclosures target:", "opts":["All suppliers globally","Top 75% of purchases/sales by value","Only Tier-1 vendors","Subsidiaries only"], "a":1, "why":"Value chain covers partners forming 75% of purchases/sales by value.", "link":SEBI},
 {"q":"BRSR applied from which financial year?", "opts":["FY 2020-21","FY 2021-22","FY 2022-23","FY 2024-25"], "a":2, "why":"First mandatory filings: FY 2022-23.", "link":SEBI},
 {"q":"Employee well-being is which principle?", "opts":["P1","P3","P6","P8"], "a":1, "why":"P3 = employee well-being, safety, training."},
 {"q":"Environment protection is which principle?", "opts":["P2","P4","P6","P9"], "a":2, "why":"P6 = environment."},
 {"q":"Ethics, transparency & accountability is which principle?", "opts":["P1","P5","P7","P9"], "a":0, "why":"P1 = ethics, transparency, accountability."},
 {"q":"Inclusive growth & equitable development is which principle?", "opts":["P4","P6","P8","P9"], "a":2, "why":"P8 = inclusive growth and CSR."},
 {"q":"Customer value & responsible service is which principle?", "opts":["P2","P7","P9","P5"], "a":2, "why":"P9 = customer value."},
 {"q":"Human rights is which principle?", "opts":["P3","P5","P6","P8"], "a":1, "why":"P5 = human rights."},
 {"q":"Stakeholder engagement is which principle?", "opts":["P4","P5","P7","P8"], "a":0, "why":"P4 = stakeholder engagement and grievance."},
 {"q":"Sustainable goods & services is which principle?", "opts":["P2","P3","P6","P9"], "a":0, "why":"P2 = sustainable products/services."},
 {"q":"Public policy advocacy & governance is which principle?", "opts":["P1","P5","P7","P8"], "a":2, "why":"P7 = public policy engagement."},
 {"q":"LTIFR measures:", "opts":["Labour turnover","Lost-time injury frequency (safety)","Long-term investment returns","Litigation frequency"], "a":1, "why":"LTIFR = lost-time injury frequency rate (P3)."},
 {"q":"Gender diversity of workforce maps primarily to:", "opts":["P1","P3","P8","P9"], "a":1, "why":"Workforce composition sits under P3."},
 {"q":"Mandatory CSR spend (2% of average net profit) comes from:", "opts":["SEBI LODR","Companies Act 2013, s.135","Income Tax Act","NGRBC"], "a":1, "why":"Section 135, Companies Act 2013.", "link":MCA},
 {"q":"BRSR ‘Lite’ is intended for:", "opts":["Top 100 companies","Voluntary / smaller filers","PSUs only","Foreign subsidiaries"], "a":1, "why":"Lite is a simplified starter for voluntary adopters."},
 {"q":"Energy intensity is typically expressed per:", "opts":["Employee","Rupee of turnover or unit of production","Square foot of office","Litre of water"], "a":1, "why":"Intensity normalises by turnover or output."},
 {"q":"Which is NOT a GHG Protocol scope?", "opts":["Scope 1","Scope 2","Scope 3","Scope 4"], "a":3, "why":"Only Scopes 1–3 exist.", "link":GHG},
 {"q":"Reasonable assurance vs limited assurance:", "opts":["Reasonable is deeper and higher confidence","Limited is deeper","Both identical","Reasonable is internal only"], "a":0, "why":"Reasonable = more evidence, positive-form opinion."},
 {"q":"XBRL in BRSR filings enables:", "opts":["Faster printing","Machine-readable structured disclosure","Video submissions","Encrypted storage"], "a":1, "why":"XBRL tags disclosures for programmatic use."},
 {"q":"Water withdrawal in water-stressed areas is reported under:", "opts":["P4","P6","P8","Section A only"], "a":1, "why":"A P6 environment indicator."},
 {"q":"Stakeholder consultation & grievance mechanisms are core to:", "opts":["P2","P4","P6","P9"], "a":1, "why":"P4 requires structured engagement and redressal."},

 {"q":"Read the extract and answer.", "table":"| KPI | FY 2023-24 | FY 2024-25 |\n|---|---|---|\n| Scope 1+2 (tCO2e) | 33,600 | 31,700 |\n| Water (kL) | 52,000 | 48,000 |\n| LTIFR | 4.6 | 5.1 |\n| Female % | 21 | 35 |", "opts":["Emissions worsened","Safety worsened (LTIFR rose)","Diversity worsened","Water use rose"], "a":1, "why":"LTIFR rising 4.6 → 5.1 means more lost-time injuries per hours worked — a deterioration."},
 {"q":"Study the policy checklist and answer.", "table":"| Policy | Board approved? | Last review |\n|---|---|---|\n| Environment | Yes | 2021 |\n| Human Rights | No | 2024 |\n| CSR | Yes | 2025 |", "opts":["All policies are compliant","Human Rights policy lacks board approval — a Section B gap","Environment policy is freshly reviewed","CSR policy is missing"], "a":1, "why":"Section B expects board-approved policies; an unapproved policy is a governance gap even if recently reviewed."},
 {"q":"The chart shows Scope 1+2 emissions by year. Which year recorded the largest absolute drop?", "chart":{"kind":"line","title":"Scope 1+2 (tCO2e)","labels":["FY22","FY23","FY24","FY25","FY26"],"values":[36000,35200,33600,31700,30200]}, "opts":["FY23","FY24","FY25","FY26"], "a":2, "why":"FY24→FY25 falls 1,900 tCO2e, the largest single-year drop (others: 800 / 1,600 / 1,500)."},
 {"q":"Energy intensity (GJ per ₹ Cr) is plotted below. Best interpretation?", "chart":{"kind":"line","title":"Energy intensity","labels":["FY23","FY24","FY25","FY26"],"values":[12.4,11.8,10.9,10.1]}, "opts":["Efficiency is improving even if output grows","Energy use is rising","Intensity is flat","Data is missing"], "a":0, "why":"Falling intensity = less energy per unit of turnover — an efficiency gain regardless of absolute energy."},
 {"q":"A director receives a draft BRSR where Scope 2 emissions were excluded from the assurance provider's scope. What is the correct response?", "scenario":"The assurance report states ‘limited to Scope 1 and Core social KPIs'. The board paper claims ‘BRSR Core fully assured'.", "opts":["Approve — partial assurance is acceptable to claim full assurance","Correct the board paper to state exactly what was assured and plan to extend scope next cycle","Remove Scope 2 from the report entirely","Ask the auditor to verbally confirm Scope 2"], "a":1, "why":"Assurance claims must match the engagement scope precisely; overstating assurance is a disclosure and governance failure.", "link":SEBI},
 {"q":"Supplier ESG data covers 60% of purchase value; BRSR Core expects value-chain coverage of top 75%. What should the company disclose?", "scenario":"The sustainability team proposes writing ‘value-chain coverage: adequate'.", "opts":["Write ‘adequate' to avoid detail","Disclose the actual 60% coverage and the plan/timeline to reach 75%","Omit the value-chain section","Report 75% as an estimate"], "a":1, "why":"Honest partial coverage with a remediation timeline is defensible; vague or inflated claims are not.", "link":SEBI},
 {"q":"Which items belong to Section A (General Disclosures)?", "multi":True, "opts":["Employee count by gender & category","CSR spend details","Grievance-redressal mechanism","Scope-wise GHG emissions intensity"], "a":[0,1,2], "why":"GHG intensity belongs to Section C (P6); Section A holds profile, workforce, CSR and grievance basics."},
 {"q":"Which of these are BRSR Core KPI families?", "multi":True, "opts":["GHG emissions (Scope 1+2)","Water withdrawal & intensity","Gender diversity & wage ratio","Marketing spend per region"], "a":[0,1,2], "why":"Core KPIs cover environmental and social essentials; marketing spend is not an ESG KPI.", "link":SEBI},
 {"q":"Match the indicator to its principle: ‘% of operations assessed for human-rights risks'.", "opts":["P3","P4","P5","P6"], "a":2, "why":"Human-rights assessments are P5 essential indicators."},
 {"q":"You upload a file with columns: State, District, Census 2001, Census 2011 (one row per district). Which data shape is this?", "opts":["Long time-series","Wide (years as columns)","Cross-sectional snapshot","Unstructured"], "a":1, "why":"Years sit in column headers — the tool must melt/unpivot it before trend analysis."},
 {"q":"Which sources provide ENTITY-level ESG data (vs macro statistics)?", "multi":True, "opts":["Company BRSR PDFs on BSE/NSE","MCA National CSR portal company-wise spend","Census sex-ratio tables","Periodic Labour Force Survey"], "a":[0,1], "why":"Census and PLFS are national/statistical aggregates; filings and MCA CSR records are entity-level."},
 {"q":"Why does the tool refuse to draw a share-pie when some category totals are negative (e.g., losses)?", "opts":["Pie charts are deprecated","Negative slices make composition percentages meaningless/misleading","Plotly cannot render negatives","It is a licensing restriction"], "a":1, "why":"A pie implies parts-of-a-whole; negative parts break that interpretation — bars handle negatives honestly."},
 {"q":"From the assurance register extract, which provider assured the most companies?", "table":"| Company | Assured? | Provider |\n|---|---|---|\n| Wipro | Yes | Deloitte Haskins & Sells |\n| Voltas | Yes | TUV India |\n| Vedanta | Yes | S.R. Battliboi |\n| Welspun | Yes | Intertek |\n| Xpro | No | — |", "opts":["Deloitte Haskins & Sells","TUV India","Each provider appears once — no ‘most'","Intertek"], "a":2, "why":"With one engagement each, no provider dominates; reading registers carefully avoids over-claiming patterns."},
 {"q":"A director asks why Principle 5 shows ‘Not assessed' on the practice dashboard. Correct explanation?", "scenario":"The imported file contains only emissions, energy and CSR columns.", "opts":["The tool is broken","No imported metric maps to human-rights keywords, so P5 has no evidence","P5 is optional under SEBI","Human rights cannot be measured"], "a":1, "why":"Tiles reflect evidence present in the data; absence of mapped metrics yields ‘Not assessed', not failure."},
 {"q":"Which aggregation rules are appropriate for RATIO metrics (%, intensity, sex ratio)?", "multi":True, "opts":["Average across units","Weighted average where weights exist","Simple Sum across units","Count of rows"], "a":[0,1], "why":"Summing ratios (e.g., sex ratios of districts) is mathematically meaningless; averages or weighted averages preserve interpretation."},
 {"q":"The line shows national CSR spend (₹ Cr) 2014-15 → 2022-23. Best description?", "chart":{"kind":"line","title":"National CSR spend","labels":["14-15","15-16","16-17","17-18","18-19","19-20","20-21","21-22","22-23"],"values":[10066,14517,14543,17099,20218,24966,26211,26616,29988]}, "opts":["Roughly tripled over nine years with steady growth","Flat since 2016","Declining after 2020","Doubled then halved"], "a":0, "why":"10,066 → 29,988 ≈ 3x with consistent upward movement — a growth trend, not volatility."},
 {"q":"In a heat map where each row is scaled to its own min–max, a dark cell means:", "opts":["The value is high in absolute terms","The value is high relative to that metric's own range","The value is missing","The value failed validation"], "a":1, "why":"Row-wise scaling compares a metric against itself over time; cross-metric magnitude needs a different normalisation."},
 {"q":"An extraction pipeline flags some BRSR rows ‘extraction_confidence: MEDIUM'. Why?", "scenario":"Rows came from PDF text-mining; others came from XBRL.", "opts":["PDFs are encrypted","PDF text-mining is heuristic and needs human QA, while XBRL is structured and exact","MEDIUM means the company restated figures","It is a random audit sample"], "a":1, "why":"XBRL parses deterministically (HIGH); PDF heuristics can mis-read tables, hence MEDIUM + QA queue."},
 {"q":"Which global frameworks are commonly aligned with BRSR for international credibility?", "multi":True, "opts":["GRI Standards","SASB Standards","TCFD recommendations","ISO 9001 (quality management)"], "a":[0,1,2], "why":"GRI/SASB/TCFD are sustainability disclosure frameworks; ISO 9001 is a quality-management standard."},
 {"q":"Read the workforce extract and answer.", "table":"| Category | Permanent | Other than permanent |\n|---|---|---|\n| Male | 8,200 | 1,400 |\n| Female | 2,800 | 600 |", "opts":["Female share of permanent workforce ≈ 25.5%","Female share ≈ 50%","Permanent staff = 9,600","Other-than-permanent total = 3,000"], "a":0, "why":"2,800 / (8,200+2,800) = 25.45%; permanent total is 11,000 and non-permanent 2,000 — the other options misread the table."},
]